version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./cache:/data

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'hamyarsale'
      MYSQL_ROOT_PASSWORD: 'a6766581'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
