SELLOORA_MYSQL_MAIN_HOST: "localhost"
SELLOORA_MYSQL_MAIN_PORT: "3306"
SELLOORA_MYSQL_MAIN_DB: "selloora"
SELLOORA_MYSQL_MAIN_USER: "root"
SELLOORA_MYSQL_MAIN_PASSWORD: "q6766581Amirex"

SELLOORA_REDIS_HOST: "localhost"
SELLOORA_REDIS_PORT: 6379
SELLOORA_REDIS_DB: 1


SERVER_HOST: "0.0.0.0"
SERVER_PORT: "8585"
