HAMYARSALE_MYSQL_HOST: "192.168.241.128"
HAMYARSALE_MYSQL_PORT: "3306"
HAMYARSALE_MYSQL_DB: "hamyarsale"
HAMYARSALE_MYSQL_USER: "root"
HAMYARSALE_MYSQL_PASSWORD: "a6766581"

HAMYARSALE_REDIS_HOST: "192.168.241.128"
HAMYARSALE_REDIS_PORT: 6379
HAMYARSALE_REDIS_DB: 1


SERVER_HOST: "0.0.0.0"
SERVER_PORT: "8585"
