name: ci_selloora

#on:
#  push:
#    tags:
#      - 'release-*'
on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/selloora-backend:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: update docker compose from latest image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /root
            rm -rf selloora_backend
            rm -rf selloora_frontend
            rm -rf docker-stack
            git clone git@github.com:amirex128/docker-stack.git
            git clone git@github.com:amirex128/selloora_frontend.git
            git clone git@github.com:amirex128/selloora_backend.git
            cd /root/selloora_frontend
            docker build -t selloora-frontend:latest .
            cd /root/docker-stack
            cat /root/dockerpassword | docker login -u amirex128 --password-stdin
            rm /etc/resolv.conf
            echo -e "nameserver 178.22.122.100 \nnameserver 185.51.200.2 \noptions edns0" >> /etc/resolv.conf
            docker compose -f docker-compose-server.yml up -d --build
            rm /etc/resolv.conf
            echo -e "nameserver 8.8.8.8 \nnameserver 8.8.4.4 \noptions edns0" >> /etc/resolv.conf
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 5426495351
          token: 5764924007:AAHSOlyZZWF7NL6_P-jiY2RxLl2-AJsgKGk
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}